# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "The Contrafabulists Podcast"
description: "Welcome to the Contrafabulists podcast, Kin Lane and Audrey Watters weekly dissection of the latest technology myth-making."
alt_description: "A Hack Education & API Evangelist Production"
subtitle: "The Week's Tech Fables, Dismantled"

email: info@contrafabulists.com
logo: "/assets/images/cog.jpg"
alt_logo: "/assets/images/cog.jpg"
cover: "/assets/images/owl.jpg"
covercredits: "http://bryanmmathers.com"

name: 'Contrafabulists'
author: 'Contrafabulists'
author_image: "/assets/images/author.png"
author_email: "info@contrafabulists.com"

keywords: 'technology, politics'

paginate:	5
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title

url: "http://podcast.techgypsi.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle:

# social icons and sharing options
social:
  - icon:   twitter
    url:    https://twitter.com/contrafabulists
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:   facebook
    url: https://facebook.com/contrafabulists  
    desc: Like me on facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/Techgypsies/podcast
    desc:   Fork me on github
    share_url:
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:
 #   desc:
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://podcast.techgypsi.es/blog.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:info@contrafabulists.com
    desc: Email
    share_url:
    share_title:
    share_link:
