# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "The Tech Gypsies Podcast"
description: "Welcome to the Tech Gypsies podcast, Kin Lane and Audrey Watters (hopefully) weekly discussion of the latest technology news."
alt_description: "A Hack Education & API Evangelist Production"
subtitle: "The Week's Tech News, Scrutinized"

email: kinlane@gmail.com
logo: "/assets/images/tech-gypsies-podcast-1500.png"
alt_logo: "/assets/images/logo.png"
cover: "/assets/images/path.jpg"
covercredits: "https://www.flickr.com/photos/143298399@N03/28631245604/in/dateposted/"

name: 'Tech Gypsies'
author: 'Tech Gypsies'
author_image: "/assets/images/author.png"
author_email: "info@kinlane.com"

keywords: 'technology, politics'

paginate:	5
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title

url: "http://podcast.techgypsi.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle:

# social icons and sharing options
social:
  - icon:
    url:
    desc:
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:
    url:
    desc:
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/Techgypsies/podcast
    desc:   Fork me on github
    share_url:
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:
 #   desc:
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://podcast.techgypsi.es/blog.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:kinlane@gmail.com
    desc: Email
    share_url:
    share_title:
    share_link:
